# Generated by Django 5.2.17 on 2026-09-15 09:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("savings", "Savings"),
                            ("other", "Other"),
                        ],
                        default="card",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="initial balance",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="archived"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "ordering": ["is_archived", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        default="expense",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="color"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="finance.category",
                        verbose_name="parent category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="First day of the month", verbose_name="month"
                    ),
                ),
                (
                    "limit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="limit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget",
                "verbose_name_plural": "budgets",
                "ordering": ["-month", "category__name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_field",
                    models.CharField(
                        choices=[
                            ("counterparty", "Counterparty"),
                            ("note", "Payment reference"),
                        ],
                        default="counterparty",
                        max_length=20,
                        verbose_name="field",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("contains", "Contains"),
                            ("startswith", "Starts with"),
                            ("exact", "Exact match"),
                        ],
                        default="contains",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                ("pattern", models.CharField(max_length=255, verbose_name="value")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower number wins",
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "category rule",
                "verbose_name_plural": "category rules",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="file")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rows_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="rows in file"
                    ),
                ),
                (
                    "rows_imported",
                    models.PositiveIntegerField(default=0, verbose_name="imported"),
                ),
                (
                    "rows_skipped",
                    models.PositiveIntegerField(
                        default=0, verbose_name="skipped as duplicates"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "statement import",
                "verbose_name_plural": "statement imports",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(max_length=255, verbose_name="counterparty"),
                ),
                (
                    "avg_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="average amount"
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(verbose_name="day of month"),
                ),
                (
                    "period_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="period, days"
                    ),
                ),
                (
                    "occurrences",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="occurrences found"
                    ),
                ),
                ("last_seen", models.DateField(verbose_name="last seen")),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, verbose_name="confirmed by user"
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(default=False, verbose_name="dismissed"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring payment",
                "verbose_name_plural": "recurring payments",
                "ordering": ["-avg_amount"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "counterparty",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="counterparty"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("import", "Imported")],
                        default="manual",
                        max_length=10,
                        verbose_name="source",
                    ),
                ),
                (
                    "dedup_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.account",
                        verbose_name="account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.importbatch",
                    ),
                ),
                (
                    "transfer_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="finance.account",
                        verbose_name="destination account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_account_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name", "kind"), name="unique_category_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "month"), name="unique_budget_per_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringpayment",
            constraint=models.UniqueConstraint(
                fields=("user", "counterparty"), name="unique_recurring_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-date"], name="finance_tra_user_id_e81357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "kind"], name="finance_tra_user_id_89fcf4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_hash", ""), _negated=True),
                fields=("user", "dedup_hash"),
                name="unique_imported_transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="transaction_amount_positive",
            ),
        ),
    ]
