# Generated by Django 5.2.17 on 2026-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringpayment",
            name="kind",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
