# Generated by Django 5.2.17 on 2026-09-25 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_recurringpayment_kind"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recurringpayment",
            name="unique_recurring_per_user",
        ),
        migrations.AddConstraint(
            model_name="recurringpayment",
            constraint=models.UniqueConstraint(fields=("user", "counterparty", "kind"), name="unique_recurring_per_user"),
        ),
    ]
